'use strict';
const $=id=>document.getElementById(id),C=TempCore;
const state={file:null,buffer:null,meta:null,source:null,index:0,points:[],results:[],busy:false,cancel:false,snapshot:null,previewToken:0,boxes:null,segments:null,confirmed:null};
const frame=$('frame'),ctx=frame.getContext('2d',{willReadFrequently:true}),crop=$('crop'),cropctx=crop.getContext('2d');
const controls=['autoFit','file','capture','interval','zero','digits','threshold','preset','saveConfig','loadConfig','undo','reset','prev','next','seek','frameNo','jump','run'];
const notice=(text,error=false)=>{$('notice').textContent=text;$('notice').classList.toggle('error',error);};
const time=s=>[Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(v=>Number.isInteger(v)?String(v).padStart(2,'0'):v.toFixed(2).padStart(5,'0')).join(':');
function settings(){const capture=+$('capture').value,interval=+$('interval').value;return {capture,interval,step:C.stepFor(capture,interval),zero:$('zero').checked};}
function config(){if(!state.meta)throw Error('先に動画を開いてください。');return {digitBoxes:state.boxes??undefined,segmentBoxes:state.segments??undefined,segmentConfirmed:state.confirmed??undefined,digits:+$('digits').value,corners:state.points.map(p=>[...p]),threshold:+$('threshold').value,image_size:[state.meta.width,state.meta.height]};}
function invalidate(){state.results=[];state.snapshot=null;$('results').hidden=true;}
function available(){let has=!!state.meta,ready=has&&state.points.length===4;for(const id of controls)$(id).disabled=state.busy||(!has&&!['autoFit','file','capture','interval','zero','digits','threshold'].includes(id));$('run').disabled=state.busy||!ready;$('autoFit').disabled=state.busy||!ready;$('preset').disabled=state.busy||!matchingPreset();$('stop').hidden=!state.busy;$('pointCount').textContent=state.points.length+' / 4点';$('calibrationStatus').textContent=state.segments?`位置確認：${state.confirmed.flat().filter(Boolean).length}/${state.confirmed.flat().length}本。黄枠は未確認（結果は要確認）。`:'桁・セグメントの位置合わせは未実行です。';}
function refresh(){available();try{const s=settings();
$('equation').textContent=`${s.capture}秒 × ${s.step}コマ = ${s.interval}分`;
if(state.meta){let n=Math.max(0,Math.floor((state.meta.count-1)/s.step)+1-(s.zero?0:1));$('estimate').textContent=`${n}件を抽出予定 · 最終コマ ${time((state.meta.count-1)*s.capture)}`;}$('position').textContent=`実経過 ${time(state.index*s.capture)}`;
}catch(e){$('equation').textContent='時間の設定を確認';$('estimate').textContent=e.message;$('run').disabled=true;}}
function draw(){if(!state.source)return;ctx.putImageData(state.source,0,0);ctx.strokeStyle='#b5f969';ctx.fillStyle='#b5f969';ctx.lineWidth=Math.max(3,frame.width/350);const pts=state.points;if(pts.length){ctx.beginPath();ctx.moveTo(...pts[0]);for(const p of pts.slice(1))ctx.lineTo(...p);if(pts.length===4)ctx.closePath();ctx.stroke();}pts.forEach(([x,y],i)=>{ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill();ctx.font='bold 22px sans-serif';ctx.fillText(i+1,x+13,y-12);});}
function preview(){if(!state.source||state.points.length!==4){$('reading').textContent='— ℃';$('readStatus').textContent='範囲を指定してください';$('readStatus').className='badge';cropctx.clearRect(0,0,crop.width,crop.height);return;}try{let c=config(),r=C.recognize(state.source,c);crop.width=r.width;crop.height=r.height;cropctx.putImageData(new ImageData(r.data,r.width,r.height),0,0);r.regions.forEach((row,k)=>row.forEach(([x0,y0,x1,y1],i)=>{cropctx.strokeStyle=state.confirmed?.[k]?.[i]===false?'#d89200':r.rates[k][i]>=c.threshold?'#acff52':'#f05b4b';cropctx.lineWidth=2;cropctx.strokeRect(x0,y0,x1-x0,y1-y0);}));$('reading').textContent=state.segments?r.text+' ℃':'位置合わせ前';$('readStatus').textContent=!state.segments?'桁・セグメントを自動調整してください':r.status==='OK'?'点灯パターン一致':'要確認';$('readStatus').className='badge '+(r.status==='OK'?'ok':'review');}catch(e){notice(e.message,true);$('readStatus').textContent='範囲を指定し直してください';$('run').disabled=true;}}
async function decode(index){const k=state.meta.chunks[index];if(!k)throw Error('指定コマがありません。');const blob=new Blob([new Uint8Array(state.buffer,k.start,k.length)],{type:'image/jpeg'});const bitmap=await createImageBitmap(blob);const can=document.createElement('canvas');can.width=state.meta.width;can.height=state.meta.height;const c=can.getContext('2d',{willReadFrequently:true});c.drawImage(bitmap,0,0);bitmap.close();return c.getImageData(0,0,can.width,can.height);}
async function show(index){const token=++state.previewToken;index=Math.max(0,Math.min(state.meta.count-1,index));const src=await decode(index);if(token!==state.previewToken)return;state.source=src;state.index=index;frame.width=src.width;frame.height=src.height;$('frameNo').value=index;$('seek').value=index;draw();refresh();preview();}
const safe=fn=>async(...args)=>{try{await fn(...args);}catch(e){notice(e.message,true);}};
$('file').addEventListener('change',safe(async()=>{const f=$('file').files[0];if(!f)return;if(f.size>1024*1024*1024)throw Error('この版では1GB以下の動画を選んでください。');notice('動画を読み込んでいます…');state.busy=true;available();try{const buffer=await f.arrayBuffer(),meta=C.parseAVI(buffer);if(meta.width<1||meta.height<1||meta.width*meta.height>40000000)throw Error('画像サイズが大きすぎるか不正です。');state.previewToken++;Object.assign(state,{file:f,buffer,meta,points:[],index:0,source:null,boxes:null,segments:null,confirmed:null});ctx.clearRect(0,0,frame.width,frame.height);invalidate();$('seek').max=meta.count-1;$('frameNo').max=meta.count-1;$('fileName').textContent=f.name;$('fileInfo').textContent=`${meta.width} × ${meta.height} px · ${meta.count}コマ`;$('empty').hidden=true;await show(0);notice('数字の4隅を指定してください。検証済みの動画には専用設定も使えます。');}finally{state.busy=false;refresh();}}));
frame.addEventListener('click',safe(e=>{if(!state.source||state.busy||state.points.length===4)return;let b=frame.getBoundingClientRect(),scale=Math.min(b.width/frame.width,b.height/frame.height),ox=(b.width-frame.width*scale)/2,oy=(b.height-frame.height*scale)/2;let x=(e.clientX-b.left-ox)/scale,y=(e.clientY-b.top-oy)/scale;if(x<0||y<0||x>=frame.width||y>=frame.height)return;state.boxes=null;state.segments=null;state.confirmed=null;state.points.push([x,y]);invalidate();draw();refresh();preview();}));
function matchingPreset(){return state.file&&VIDEO_PRESETS.find(p=>p.name.toLowerCase()===state.file.name.toLowerCase()&&p.size===state.file.size&&p.frames===state.meta?.count);}
async function calibrate(){if(state.busy)throw Error('処理中です。');const c=config();delete c.digitBoxes;delete c.segmentBoxes;delete c.segmentConfirmed;C.validate(c,state.meta.width,state.meta.height);state.busy=true;state.previewToken++;available();state.cancel=false;try{const flats=[],n=Math.min(30,state.meta.count);for(let k=0;k<n;k++){if(state.cancel)throw Error('位置合わせを中止しました。');const index=Math.floor(k*(state.meta.count-1)/Math.max(1,n-1));flats.push(C.rectify(await decode(index),c));$('progressText').textContent=`桁の位置合わせ ${k+1}/${n}`;await new Promise(r=>setTimeout(r,0));}const digitBoxes=C.fitCalibration(flats,c);$('progressText').textContent='各セグメントの位置を確認中…';await new Promise(r=>setTimeout(r,0));if(state.cancel)throw Error('位置合わせを中止しました。');const fitted=C.fitSegments(flats,{...c,digitBoxes});state.boxes=digitBoxes;state.segments=fitted.segmentBoxes;state.confirmed=fitted.segmentConfirmed;invalidate();$('calibrationStatus').textContent=`${n}コマで確認：${state.confirmed.flat().filter(Boolean).length}/${c.digits*7}本。黄枠は未確認（結果は要確認）。`;$('progressText').textContent='位置合わせ完了。温度を抽出できます';notice('各桁・各セグメントの枠を合わせました。数字と判定枠を確認してください。');}finally{state.busy=false;refresh();preview();}}
$('autoFit').onclick=safe(calibrate);
$('preset').onclick=safe(async()=>{const preset=matchingPreset();if(!preset)throw Error('この動画に一致する検証済み設定はありません。手動で範囲を指定してください。');const c=structuredClone(preset.config);C.validate(c,state.meta.width,state.meta.height);state.points=c.corners;state.boxes=null;state.segments=null;state.confirmed=null;$('digits').value=c.digits;$('threshold').value=c.threshold;invalidate();draw();refresh();await calibrate();});
$('undo').onclick=()=>{state.boxes=null;state.segments=null;state.confirmed=null;state.points.pop();invalidate();draw();refresh();preview();};$('reset').onclick=()=>{state.boxes=null;state.segments=null;state.confirmed=null;state.points=[];invalidate();draw();refresh();preview();};
for(const id of ['capture','interval','zero','digits','threshold'])$(id).addEventListener('input',()=>{if(id==='digits'){state.boxes=null;state.segments=null;state.confirmed=null;}invalidate();refresh();preview();});
$('prev').onclick=safe(()=>show(state.index-settings().step));$('next').onclick=safe(()=>show(state.index+settings().step));$('jump').onclick=safe(()=>{const n=+$('frameNo').value;if(!Number.isInteger(n)||n<0||n>=state.meta.count)throw Error('コマ番号が範囲外です。');return show(n);});$('seek').onchange=safe(()=>show(+$('seek').value));
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
$('saveConfig').onclick=safe(()=>{const c=config();C.validate(c,state.meta.width,state.meta.height);download(new Blob([JSON.stringify(c,null,2)],{type:'application/json'}),'温度ログ_範囲設定.json');});$('loadConfig').onclick=()=>$('configFile').click();$('configFile').onchange=safe(async()=>{let f=$('configFile').files[0];if(!f)return;const c=JSON.parse(await f.text());C.validate(c,state.meta.width,state.meta.height);state.boxes=c.digitBoxes??null;state.segments=c.segmentBoxes??null;state.confirmed=c.segmentConfirmed??null;state.points=c.corners;$('digits').value=c.digits;$('threshold').value=c.threshold;invalidate();draw();refresh();preview();$('configFile').value='';});
function chart(){const can=$('chart'),c=can.getContext('2d'),w=can.width,h=can.height,left=62,right=24,top=20,bottom=48;let vals=state.results.filter(r=>r.value!==null),max=Math.max(100,...vals.map(r=>r.value))*1.1,last=Math.max(1,...state.results.map(r=>r.minute));c.clearRect(0,0,w,h);c.fillStyle='#fff';c.fillRect(0,0,w,h);c.font='14px sans-serif';c.lineWidth=1;c.textAlign='right';for(let i=0;i<=5;i++){let y=h-bottom-i*(h-top-bottom)/5;c.strokeStyle='#e0e9ea';c.beginPath();c.moveTo(left,y);c.lineTo(w-right,y);c.stroke();c.fillStyle='#637b83';c.fillText(Math.round(max*i/5),left-10,y+5);}c.textAlign='center';for(let i=0;i<=5;i++){let x=left+i*(w-left-right)/5;c.fillText((last*i/5).toFixed(1).replace('.0',''),x,h-bottom+23);}c.fillText('実経過時間［分］',w/2,h-6);c.fillText('℃',27,19);c.strokeStyle='#006e74';c.lineWidth=3;c.beginPath();let drawing=false;for(const r of state.results){if(r.value===null){drawing=false;continue;}let x=left+r.minute/last*(w-left-right),y=h-bottom-r.value/max*(h-top-bottom);if(!drawing)c.moveTo(x,y);else c.lineTo(x,y);drawing=true;}c.stroke();for(const r of vals){c.beginPath();c.arc(left+r.minute/last*(w-left-right),h-bottom-r.value/max*(h-top-bottom),3.5,0,Math.PI*2);c.fillStyle='#006e74';c.fill();}}
function renderResults(){const bad=state.results.filter(r=>r.status!=='OK').length;$('resultTitle').textContent=`${state.results.length}件を抽出 · 要確認 ${bad}件`;$('rows').replaceChildren();state.results.forEach(r=>{let tr=document.createElement('tr');if(r.status!=='OK')tr.className='review';for(const v of [r.minute,r.value===null?'—':r.value,r.status==='OK'?'OK':`要確認 / ${r.candidate}`]){let td=document.createElement('td');td.textContent=v;tr.append(td);}tr.onclick=safe(async()=>{if(!state.busy){await show(r.frame);frame.scrollIntoView({behavior:'smooth',block:'center'});}});$('rows').append(tr);});$('results').hidden=false;chart();}
$('run').onclick=safe(async()=>{const s=settings();if(!state.boxes||!state.segments)await calibrate();const c=config();C.validate(c,state.meta.width,state.meta.height);if(state.meta.count<=(s.zero?0:s.step))throw Error('抽出対象がありません。0分を含めるか間隔を短くしてください。');state.previewToken++;state.busy=true;state.cancel=false;invalidate();state.snapshot={...s,config:c};available();$('progress').max=Math.floor((state.meta.count-1)/s.step)+1-(s.zero?0:1);$('progress').value=0;let out=[];try{for(let index=s.zero?0:s.step;index<state.meta.count;index+=s.step){if(state.cancel)break;const src=await decode(index),r=C.recognize(src,c),can=document.createElement('canvas');can.width=r.width;can.height=r.height;can.getContext('2d').putImageData(new ImageData(r.data,r.width,r.height),0,0);const png=new Uint8Array(await (await new Promise(resolve=>can.toBlob(resolve,'image/png'))).arrayBuffer());out.push({minute:index*s.capture/60,seconds:index*s.capture,frame:index,value:r.value,status:r.status,candidate:r.text,png});$('progress').value=out.length;$('progressText').textContent=`${out.length}件処理 · 実経過 ${index*s.capture/60}分`;await new Promise(resolve=>setTimeout(resolve,0));}if(state.cancel){notice('中止しました。途中の結果は出力していません。');$('progressText').textContent='処理を中止しました';state.snapshot=null;}else{state.results=out;renderResults();notice('抽出が完了しました。Excelに保存してね。');$('progressText').textContent=`完了：${out.length}件`;$('results').scrollIntoView({behavior:'smooth',block:'start'});}}catch(e){state.snapshot=null;throw e;}finally{state.busy=false;available();}});
$('stop').onclick=()=>{state.cancel=true;};
$('excel').onclick=safe(async()=>{$('excel').disabled=true;try{notice('Excelを作成しています…');const rows=state.results.slice(),snapshot=structuredClone(state.snapshot),filename=state.file.name;let bytes=await makeTemperatureWorkbook(rows,snapshot,filename);download(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),filename.replace(/\.avi$/i,'')+`_${snapshot.interval}分ごと温度.xlsx`);notice('Excelを保存しました。ダウンロード先を確認してください。');}finally{$('excel').disabled=false;}});
$('csv').onclick=safe(()=>{let rows=[['実経過時間[分]','温度[℃]','判定','認識候補','実経過時間[秒]','コマ番号'],...state.results.map(r=>[r.minute,r.value??'',r.status,r.candidate,r.seconds,r.frame])];download(new Blob(['\ufeff'+rows.map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),'温度ログ.csv');});
$('helpBtn').onclick=()=>$('help').showModal();$('closeHelp').onclick=()=>$('help').close();
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_temperature_extraction_state',description:'現在の動画名、時間設定、範囲、抽出結果の件数を読む。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({file:state.file?.name??null,frame:state.index,settings:settings(),points:state.points,rows:state.results.length,review:state.results.filter(r=>r.status!=='OK').length})})).catch(()=>{});}catch{}}
refresh();
