/* Temperature Log: no server, no trained model. */
(function(root){
'use strict';
const patterns={'1110111':'0','0010010':'1','1011101':'2','1011011':'3','0111010':'4','1101011':'5','1101111':'6','1010010':'7','1110010':'7','1111111':'8','1111011':'9','0000000':' '};
const zones=[[.30,.025,.70,.15],[.02,.20,.33,.40],[.78,.20,.96,.40],[.30,.445,.70,.555],[.02,.60,.33,.80],[.78,.60,.96,.80],[.30,.85,.70,.975]];
const preset={digits:3,corners:[[406,302],[773,276],[748,465],[389,505]],threshold:.3,image_size:[1280,720]};
function stepFor(seconds,minutes){const r=minutes*60/seconds;if(!Number.isFinite(r)||!Number.isFinite(seconds)||!Number.isFinite(minutes)||seconds<=0||minutes<=0||r<1||Math.abs(r-Math.round(r))>1e-8)throw Error('抽出間隔は撮影間隔の整数倍にしてね。10秒撮影なら1分＝6コマ。');return Math.round(r);}
function validate(c,w,h){if(!Number.isInteger(c.digits)||c.digits<1||c.digits>8)throw Error('桁数は1〜8にしてください。');if(!c.corners||c.corners.length!==4)throw Error('数字の外周を4点で指定してください。');if(c.image_size?.[0]!==w||c.image_size?.[1]!==h)throw Error('動画と設定の画像サイズが違います。');if(!(c.threshold>0&&c.threshold<1))throw Error('点灯閾値は0より大きく1未満にしてください。');if(c.digitBoxes){if(!Array.isArray(c.digitBoxes)||c.digitBoxes.length!==c.digits||c.digitBoxes.some(b=>!Array.isArray(b)||b.length!==4||!b.every(Number.isFinite)||b[0]<0||b[1]<0||b[2]>c.digits*100||b[3]>200||b[2]<=b[0]||b[3]<=b[1]))throw Error('桁位置の設定が不正です。位置合わせをやり直してください。');}let area=0;for(let i=0;i<4;i++){let p=c.corners[i],q=c.corners[(i+1)%4],r=c.corners[(i+2)%4];if(p.length!==2||!p.every(Number.isFinite)||p[0]<0||p[0]>=w||p[1]<0||p[1]>=h)throw Error('点が画像の外にあります。');if((q[0]-p[0])*(r[1]-q[1])-(q[1]-p[1])*(r[0]-q[0])<=0)throw Error('左上→右上→右下→左下の順に指定してください。');area+=p[0]*q[1]-p[1]*q[0];}if(area<200)throw Error('数字全体を、もう少し広く囲んでください。');}
function solve(A,b){A=A.map((r,i)=>[...r,b[i]]);for(let i=0;i<b.length;i++){let p=i;for(let j=i+1;j<b.length;j++)if(Math.abs(A[j][i])>Math.abs(A[p][i]))p=j;[A[p],A[i]]=[A[i],A[p]];let d=A[i][i];if(Math.abs(d)<1e-10)throw Error('範囲を指定し直してください。');for(let k=i;k<=b.length;k++)A[i][k]/=d;for(let j=0;j<b.length;j++)if(j!==i){let m=A[j][i];for(let k=i;k<=b.length;k++)A[j][k]-=m*A[i][k];}}return A.map(r=>r[b.length]);}
function rectify(src,c){validate(c,src.width,src.height);const w=c.digits*100,h=200,A=[],B=[];[[0,0],[w,0],[w,h],[0,h]].forEach(([x,y],i)=>{let[u,v]=c.corners[i];A.push([x,y,1,0,0,0,-u*x,-u*y],[0,0,0,x,y,1,-v*x,-v*y]);B.push(u,v);});let a=solve(A,B);let rgba=new Uint8ClampedArray(w*h*4),mask=new Uint8Array(w*h);
for(let y=0;y<h;y++)for(let x=0;x<w;x++){let den=a[6]*(x+.5)+a[7]*(y+.5)+1;let u=(a[0]*(x+.5)+a[1]*(y+.5)+a[2])/den-.5,v=(a[3]*(x+.5)+a[4]*(y+.5)+a[5])/den-.5;u=Math.max(0,Math.min(src.width-1,u));v=Math.max(0,Math.min(src.height-1,v));let ix=Math.floor(u),iy=Math.floor(v),fx=u-ix,fy=v-iy;let base=(y*w+x)*4;for(let k=0;k<3;k++){let at=(xx,yy)=>src.data[(Math.min(yy,src.height-1)*src.width+Math.min(xx,src.width-1))*4+k];rgba[base+k]=at(ix,iy)*(1-fx)*(1-fy)+at(ix+1,iy)*fx*(1-fy)+at(ix,iy+1)*(1-fx)*fy+at(ix+1,iy+1)*fx*fy;}rgba[base+3]=255;let r=rgba[base],g=rgba[base+1],b=rgba[base+2];mask[y*w+x]=((g>110&&g>r*1.025&&g>b*1.035&&g-r>4)||(r>170&&g>190&&b>170&&g>=r*.95&&g>=b*.95))?1:0;}
return {width:w,height:h,data:rgba,mask};}
function recognize(src,c){let flat=rectify(src,c),{width:w,height:h,data:rgba,mask}=flat;
let chars=[],rates=[],weak=false;for(let digit=0;digit<c.digits;digit++){let box=c.digitBoxes?.[digit]??[digit*100,0,(digit+1)*100,h];let rs=zones.map(([x0,y0,x1,y1])=>{let sum=0,n=0;for(let y=Math.floor(box[1]+y0*(box[3]-box[1]));y<Math.floor(box[1]+y1*(box[3]-box[1]));y++)for(let x=Math.floor(box[0]+x0*(box[2]-box[0]));x<Math.floor(box[0]+x1*(box[2]-box[0]));x++){if(x>=0&&x<w&&y>=0&&y<h){sum+=mask[y*w+x];n++;}}return n?sum/n:0;});rates.push(rs);if(rs.some(v=>Math.abs(v-c.threshold)<.1))weak=true;chars.push(patterns[rs.map(v=>v>=c.threshold?'1':'0').join('')]??'?');}let text=chars.join('').trimStart(),ok=/^\d+$/.test(text)&&!weak;return {text:text||'(消灯)',value:ok?Number(text):null,status:ok?'OK':'要確認',width:w,height:h,data:rgba,mask,rates};}
// Fit each digit independently from the union of up to ten sampled frames.
// Calibration changes geometry only; it never supplies temperature values.
function greenUnion(flats){if(!flats.length)throw Error('位置合わせ用の画像がありません。');const w=flats[0].width,h=flats[0].height,mask=new Uint8Array(w*h);for(const f of flats)for(let i=0;i<mask.length;i++){let r=f.data[i*4],g=f.data[i*4+1],b=f.data[i*4+2];if(g>100&&g>r*1.15&&g>b*1.1&&g-r>18)mask[i]=1;}return {mask,w,h};}
function fitCalibration(flats,c){const {mask,w,h}=greenUnion(flats),col=new Float64Array(w);for(let y=Math.round(h*.15);y<Math.round(h*.85);y++)for(let x=0;x<w;x++)col[x]+=mask[y*w+x];const active=[];for(let x=0;x<w;x++)if(col[x]>h*.1)active.push(x);if(!active.length)throw Error('点灯部分が見つかりません。数字全体を囲み直してください。');const l=active[0],r=active[active.length-1]+1,span=(r-l)/c.digits,splits=[l];for(let i=1;i<c.digits;i++){const center=l+span*i,lo=Math.max(l,Math.floor(center-span*.22)),hi=Math.min(r,Math.floor(center+span*.22));let cut=lo;for(let x=lo+1;x<hi;x++)if(col[x]<col[cut])cut=x;splits.push(cut);}splits.push(r);
const quantile=(a,q)=>{a.sort((a,b)=>a-b);let t=(a.length-1)*q,lo=Math.floor(t),hi=Math.ceil(t);return a[lo]+(a[hi]-a[lo])*(t-lo);};const boxes=[];for(let i=0;i<c.digits;i++){let xs=[],ys=[];for(let y=0;y<h;y++)for(let x=splits[i];x<splits[i+1];x++)if(mask[y*w+x]){xs.push(x);ys.push(y);}if(xs.length<40)throw Error('全桁を検出できません。消灯中の桁も含めて囲み直してください。');const box=[quantile(xs,.005),quantile(ys,.005),Math.min(w,quantile(xs,.995)+1),Math.min(h,quantile(ys,.995)+1)];if(box[3]-box[1]<h*.35||box[2]-box[0]<span*.35)throw Error('桁の形を十分に確認できません。範囲・桁数を確認してください。');boxes.push(box);}return boxes;}
// RIFF/OpenDML traversal. Only actual video chunks inside movi are selected.
function parseAVI(buffer){let v=new DataView(buffer),u=new Uint8Array(buffer),list=[],streams=[],micro=0;let four=p=>String.fromCharCode(...u.subarray(p,p+4));if(four(0)!=='RIFF'||four(8)!=='AVI ')throw Error('AVI形式の動画を選んでください。');function walk(start,end,inMovi=false,stream=null){let p=start;for(;p+8<=end;){let id=four(p),n=v.getUint32(p+4,true),s=p+8,e=s+n;if(e>u.length||e>end&&!((/^\d\d(?:dc|db)$/.test(id)&&e-end<=8)||((id==='LIST'||id==='RIFF')&&e-end<=32)))throw Error('動画が途中で切れているか、AVIの構造が不正です。');if(id==='LIST'||id==='RIFF'){let type=four(s);let ctx=stream;if(type==='strl'){ctx={};streams.push(ctx);}if(['AVI ','AVIX','hdrl','strl','movi','rec '].includes(type))e=Math.max(e,walk(s+4,e,inMovi||type==='movi',ctx));}else if(id==='avih'&&n>=40){micro=v.getUint32(s,true);}else if(id==='strh'&&stream&&n>=48){Object.assign(stream,{type:four(s),handler:four(s+4),scale:v.getUint32(s+20,true),rate:v.getUint32(s+24,true)});}else if(id==='strf'&&stream&&n>=20){stream.width=v.getInt32(s+4,true);stream.height=Math.abs(v.getInt32(s+8,true));stream.codec=four(s+16);}else if(inMovi&&/^\d\d(?:dc|db)$/.test(id)){list.push({stream:Number(id.slice(0,2)),start:s,length:n});}p=e+(e%2);}return p;}
walk(0,u.length);let si=streams.findIndex(s=>s.type==='vids');if(si<0)throw Error('映像トラックがありません。');let s=streams[si];if(!['MJPG','JPEG','jpeg','mjpg'].includes(s.codec)&&!['MJPG','JPEG','mjpg'].includes(s.handler))throw Error('この版はMJPEG形式のAVIに対応しています。今回のTLC動画と同じ形式を選んでください。');let chunks=list.filter(x=>x.stream===si);if(!chunks.length)throw Error('映像コマが見つかりません。');for(const chunk of chunks)if(chunk.length<4||u[chunk.start]!==255||u[chunk.start+1]!==216)throw Error('JPEGではない映像コマが含まれています。');return {width:s.width,height:s.height,fps:s.rate&&s.scale?s.rate/s.scale:1e6/micro,chunks,count:chunks.length};}
const api={stepFor,validate,recognize,rectify,fitCalibration,parseAVI,preset,zones};root.TempCore=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
