(function(root){'use strict';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main',rel='http://schemas.openxmlformats.org/officeDocument/2006/relationships',pkg='http://schemas.openxmlformats.org/package/2006/relationships';
const xml=s=>'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'+s;
const relationship=(id,type,target)=>`<Relationship Id="${id}" Type="${rel}/${type}" Target="${target}"/>`;
function sheet(rows,widths,drawing=false,images=false){let data=rows.map((row,i)=>`<row r="${i+1}"${images&&i?' ht="95" customHeight="1"':''}>${row.map((v,j)=>{let addr=String.fromCharCode(65+j)+(i+1),style=i===0?' s="1"':row[2]==='要確認'?' s="2"':'';return v===null||v===undefined?`<c r="${addr}"${style}/>`:typeof v==='number'?`<c r="${addr}"${style}><v>${v}</v></c>`:`<c r="${addr}" t="inlineStr"${style}><is><t xml:space="preserve">${esc(v)}</t></is></c>`;}).join('')}</row>`).join('');return xml(`<worksheet xmlns="${ns}" xmlns:r="${rel}"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${widths.map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join('')}</cols><sheetData>${data}</sheetData>${!images?`<autoFilter ref="A1:${String.fromCharCode(64+rows[0].length)}${rows.length}"/>`:''}${drawing?'<drawing r:id="rId1"/>':''}</worksheet>`);}
const marker=(col,row)=>`<xdr:col>${col}</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>${row}</xdr:row><xdr:rowOff>0</xdr:rowOff>`;
const drawing=inside=>xml(`<xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="${rel}">${inside}</xdr:wsDr>`);
const axisTitle=t=>`<c:title><c:tx><c:rich><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="ja-JP"/><a:t>${esc(t)}</a:t></a:r></a:p></c:rich></c:tx><c:overlay val="0"/></c:title>`;
async function workbook(results,settings,fileName){if(!results.length)throw Error('抽出結果がありません。');const z=new root.JSZip();const count=results.length,last=count+1;
let rows=[['実経過時間 [分]','温度 [℃]','判定','認識候補','実経過時間 [秒]','コマ番号（0始まり）'],...results.map(r=>[r.minute,r.value,r.status,r.candidate,r.seconds,r.frame])];
const note=[['項目','内容'],['元動画',fileName],['1コマの実時間 [秒]',settings.capture],['抽出間隔 [分]',settings.interval],['0分を含める',String(settings.zero)],['抽出件数',count],['要確認件数',results.filter(r=>r.status!=='OK').length],['時間基準','先頭コマ＝0秒。コマ番号×撮影間隔。動画fpsは使わない。'],['前提','欠落・重複のない等間隔撮影。固定カメラ、黄緑色の整数表示。'],['判定','OKは点灯パターン一致。誤認することもある。要確認は温度欄が空欄。'],['設定',JSON.stringify(settings)],['作成日時',new Date().toISOString()]];
z.file('xl/worksheets/sheet1.xml',sheet(rows,[24,18,16,18,24,28],true));z.file('xl/worksheets/sheet2.xml',sheet([['実経過時間 [分]','判定','表示範囲'],...results.map(r=>[r.minute,r.status,''])],[24,18,70],true,true));z.file('xl/worksheets/sheet3.xml',sheet(note,[28,100]));
z.file('xl/styles.xml',xml(`<styleSheet xmlns="${ns}"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Calibri"/></font></fonts><fills count="4"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF16363F"/><bgColor indexed="64"/></patternFill></fill><fill><patternFill patternType="solid"><fgColor rgb="FFFFF1D9"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFill="1" applyFont="1"/><xf numFmtId="0" fontId="0" fillId="3" borderId="0" xfId="0" applyFill="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`));
z.file('xl/workbook.xml',xml(`<workbook xmlns="${ns}" xmlns:r="${rel}"><bookViews><workbookView/></bookViews><sheets>${['温度データ','確認画像','抽出条件'].map((s,i)=>`<sheet name="${s}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets><calcPr calcId="191029" fullCalcOnLoad="1"/></workbook>`));
z.file('xl/_rels/workbook.xml.rels',xml(`<Relationships xmlns="${pkg}">${[1,2,3].map(i=>relationship('rId'+i,'worksheet',`worksheets/sheet${i}.xml`)).join('')}${relationship('rId4','styles','styles.xml')}</Relationships>`));
z.file('_rels/.rels',xml(`<Relationships xmlns="${pkg}">${relationship('rId1','officeDocument','xl/workbook.xml')}</Relationships>`));
for(let i of [1,2])z.file(`xl/worksheets/_rels/sheet${i}.xml.rels`,xml(`<Relationships xmlns="${pkg}">${relationship('rId1','drawing',`../drawings/drawing${i}.xml`)}</Relationships>`));
z.file('xl/drawings/drawing1.xml',drawing(`<xdr:twoCellAnchor><xdr:from>${marker(7,1)}</xdr:from><xdr:to>${marker(19,24)}</xdr:to><xdr:graphicFrame macro=""><xdr:nvGraphicFramePr><xdr:cNvPr id="1" name="時間－温度グラフ"/><xdr:cNvGraphicFramePr/></xdr:nvGraphicFramePr><xdr:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/></xdr:xfrm><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/chart"><c:chart xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" r:id="rId1"/></a:graphicData></a:graphic></xdr:graphicFrame><xdr:clientData/></xdr:twoCellAnchor>`));
z.file('xl/drawings/_rels/drawing1.xml.rels',xml(`<Relationships xmlns="${pkg}">${relationship('rId1','chart','../charts/chart1.xml')}</Relationships>`));
let picxml='',picrels='';for(let i=0;i<count;i++){let r=results[i];if(!r.png)continue;z.file(`xl/media/image${i+1}.png`,r.png);picrels+=relationship('rId'+(i+1),'image',`../media/image${i+1}.png`);picxml+=`<xdr:oneCellAnchor><xdr:from>${marker(2,i+1)}</xdr:from><xdr:ext cx="${settings.config.digits*60*9525}" cy="1143000"/><xdr:pic><xdr:nvPicPr><xdr:cNvPr id="${i+1}" name="コマ${r.frame}"/><xdr:cNvPicPr/></xdr:nvPicPr><xdr:blipFill><a:blip r:embed="rId${i+1}"/><a:stretch><a:fillRect/></a:stretch></xdr:blipFill><xdr:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="${settings.config.digits*60*9525}" cy="1143000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></xdr:spPr></xdr:pic><xdr:clientData/></xdr:oneCellAnchor>`;}
z.file('xl/drawings/drawing2.xml',drawing(picxml));z.file('xl/drawings/_rels/drawing2.xml.rels',xml(`<Relationships xmlns="${pkg}">${picrels}</Relationships>`));
const cache=(field)=>`<c:numCache><c:formatCode>General</c:formatCode><c:ptCount val="${count}"/>${results.map((r,i)=>r[field]===null?'':`<c:pt idx="${i}"><c:v>${r[field]}</c:v></c:pt>`).join('')}</c:numCache>`;
z.file('xl/charts/chart1.xml',xml(`<c:chartSpace xmlns:c="http://schemas.openxmlformats.org/drawingml/2006/chart" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><c:chart>${axisTitle('時間－温度')}<c:plotArea><c:layout/><c:scatterChart><c:scatterStyle val="lineMarker"/><c:ser><c:idx val="0"/><c:order val="0"/><c:tx><c:v>温度</c:v></c:tx><c:spPr><a:ln w="24000"><a:solidFill><a:srgbClr val="006E74"/></a:solidFill></a:ln></c:spPr><c:xVal><c:numRef><c:f>'温度データ'!$A$2:$A$${last}</c:f>${cache('minute')}</c:numRef></c:xVal><c:yVal><c:numRef><c:f>'温度データ'!$B$2:$B$${last}</c:f>${cache('value')}</c:numRef></c:yVal></c:ser><c:axId val="10"/><c:axId val="20"/></c:scatterChart><c:valAx><c:axId val="10"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:axPos val="b"/>${axisTitle('実経過時間 [分]')}<c:crossAx val="20"/><c:crosses val="autoZero"/></c:valAx><c:valAx><c:axId val="20"/><c:scaling><c:orientation val="minMax"/></c:scaling><c:axPos val="l"/><c:majorGridlines/>${axisTitle('温度 [℃]')}<c:crossAx val="10"/><c:crosses val="autoZero"/></c:valAx></c:plotArea><c:plotVisOnly val="1"/><c:dispBlanksAs val="gap"/></c:chart></c:chartSpace>`));
let types=[['/xl/workbook.xml','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml'],['/xl/styles.xml','application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml'],...['1','2','3'].map(i=>[`/xl/worksheets/sheet${i}.xml`,'application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml']),...['1','2'].map(i=>[`/xl/drawings/drawing${i}.xml`,'application/vnd.openxmlformats-officedocument.drawing+xml']),['/xl/charts/chart1.xml','application/vnd.openxmlformats-officedocument.drawingml.chart+xml']];
z.file('[Content_Types].xml',xml(`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/>${types.map(([p,t])=>`<Override PartName="${p}" ContentType="${t}"/>`).join('')}</Types>`));return z.generateAsync({type:'uint8array',compression:'DEFLATE'});}
root.makeTemperatureWorkbook=workbook;if(typeof module!=='undefined')module.exports=workbook;
})(typeof globalThis!=='undefined'?globalThis:this);
